apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: blazing-web
  namespace: default
spec:
  secretName: blazingmicropizzas-tls-secret
  dnsNames:
  - blazingmicropizzas.westus2.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - blazingmicropizzas.westus2.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer