version: "3.7"
services:
  webapp:
    build:
      context: .
      dockerfile: ./BlazingPizza.Web/Dockerfile
    image: blazingreg.azurecr.io/blazingpizzaweb
    depends_on:
      - orders
      - menu
    networks:
      - frontend
      - backend
    ports:
      - "64590:80"
    environment:
       - "Services:Orders=http://orders:5555"
       - "Services:Menu=http://menu"
       - "Services.Auth=http://auth"
#      - "Authentication:Twitter:ConsumerKey=U9DbAaVcDPYO3RVFlDo4w"
#      - "Authentication:Twitter:ConsumerSecret=l6HWZa8F5MJmbBkGSzL6gMjgZMererT5KROxAzws9o"
  orders:
    build:
      context: .
      dockerfile: ./BlazingPizza.Orders/Dockerfile
    image: blazingreg.azurecr.io/blazingpizzaorders
    networks:
      - backend
    expose:
      - 5555
    environment:
      - "Data:Connection=mongodb://mongo:27017"
  mongo:
    image: mongo
    networks:
      - backend
    expose:
      - 27017
  menu:
    build:
      context: .
      dockerfile: ./BlazingPizza.Menu/Dockerfile
    image: blazingreg.azurecr.io/blazingpizzamenu
    networks:
      - backend
    expose:
      - 80
      - 443
networks:
  frontend:
  backend:
