version: "3.7"
services:
  webapp:
    build:
      context: .
      dockerfile: ./BlazingPizza.Web/Dockerfile
    depends_on:
      - orders
      - menu
    networks:
      - frontend
      - backend
    ports:
      - "5000:80"
    environment:
#TODO: We need TLS.
       - "Services:Orders=http://orders"
       - "Services:Menu=http://menu"
       - "Services.Auth=http://auth"
#      - "Authentication:Twitter:ConsumerKey=U9DbAaVcDPYO3RVFlDo4w"
#      - "Authentication:Twitter:ConsumerSecret=l6HWZa8F5MJmbBkGSzL6gMjgZMererT5KROxAzws9o"
  orders:
    build:
      context: .
      dockerfile: ./BlazingPizza.Orders/Dockerfile
    networks:
      - backend
    expose:
      - 80
      - 443
  menu:
    build:
      context: .
      dockerfile: ./BlazingPizza.Menu/Dockerfile
    networks:
      - backend
    expose:
      - 80
      - 443
networks:
  frontend:
  backend:
